from django.urls import path

from src.finances.views import (
    accounting,
    bank_books,
    messages,
    meter_readings,
    payment_receipts,
    requests,
    statistics,
)

app_name = "finances"

urlpatterns = [
    path(
        "requests/", requests.RequestsListView.as_view(), name="requests_list"
    ),
    path(
        "requests/ajax",
        requests.RequestsAjaxDatatableView.as_view(),
        name="requests_ajax_list",
    ),
    path(
        "requests/create/",
        requests.RequestsCreateView.as_view(),
        name="requests_create",
    ),
    path(
        "requests/<int:pk>/detail/",
        requests.RequestsDetailView.as_view(),
        name="requests_detail",
    ),
    path(
        "requests/<int:pk>/update/",
        requests.RequestsUpdateView.as_view(),
        name="requests_update",
    ),
    path(
        "requests/<int:pk>/delete/",
        requests.RequestsDeleteView.as_view(),
        name="requests_delete",
    ),
    path(
        "meter_readings/",
        meter_readings.MeterReadingsListView.as_view(),
        name="meter_readings_list",
    ),
    path(
        "meter_readings/ajax",
        meter_readings.MeterReadingsAjaxDatatableView.as_view(),
        name="meter_readings_ajax_list",
    ),
    path(
        "meter_readings/create/",
        meter_readings.MeterReadingsCreateView.as_view(),
        name="meter_readings_create",
    ),
    path(
        "meter_readings/<int:pk>/detail/",
        meter_readings.MeterReadingsDetailView.as_view(),
        name="meter_readings_detail",
    ),
    path(
        "meter_readings/<int:pk>/update/",
        meter_readings.MeterReadingsUpdateView.as_view(),
        name="meter_readings_update",
    ),
    path(
        "meter_readings/<int:pk>/delete/",
        meter_readings.MeterReadingsDeleteView.as_view(),
        name="meter_readings_delete",
    ),
    path(
        "messages/", messages.MessagesListView.as_view(), name="messages_list"
    ),
    path(
        "messages/ajax",
        messages.MessagesAjaxDatatableView.as_view(),
        name="messages_ajax_list",
    ),
    path(
        "messages/create/",
        messages.MessagesCreateView.as_view(),
        name="messages_create",
    ),
    path(
        "messages/<int:pk>/detail/",
        messages.MessagesDetailView.as_view(),
        name="messages_detail",
    ),
    path(
        "messages/<int:pk>/update/",
        messages.MessagesUpdateView.as_view(),
        name="messages_update",
    ),
    path(
        "messages/<int:pk>/delete/",
        messages.MessagesDeleteView.as_view(),
        name="messages_delete",
    ),
    # Statistics
    path(
        "statistics/",
        statistics.StatisticsDetailView.as_view(),
        name="statistics",
    ),
    # Bank books
    path(
        "bank_books/",
        bank_books.BankBooksListView.as_view(),
        name="bank_books_list",
    ),
    path(
        "bank_books/ajax",
        bank_books.BankBooksAjaxDatatableView.as_view(),
        name="bank_books_ajax_list",
    ),
    path(
        "bank_books/create/",
        bank_books.BankBooksCreateView.as_view(),
        name="bank_books_create",
    ),
    path(
        "bank_books/export/",
        bank_books.BankBooksExportView.as_view(),
        name="bank_books_export",
    ),
    path(
        "bank_books/<int:pk>/detail/",
        bank_books.BankBooksDetailView.as_view(),
        name="bank_books_detail",
    ),
    path(
        "bank_books/<int:pk>/update/",
        bank_books.BankBooksUpdateView.as_view(),
        name="bank_books_update",
    ),
    path(
        "bank_books/<int:pk>/delete/",
        bank_books.BankBooksDeleteView.as_view(),
        name="bank_books_delete",
    ),
    path(
        "ajax/bank_books/select2/",
        bank_books.BankBookSelect2View.as_view(),
        name="bank_book_select2",
    ),
    # Accounting
    path(
        "accounting/",
        accounting.AccountingListView.as_view(),
        name="accounting_list",
    ),
    path(
        "accounting/export/",
        accounting.AccountingExportView.as_view(),
        name="accounting_export",
    ),
    path(
        "accounting/ajax",
        accounting.AccountingAjaxDatatableView.as_view(),
        name="accounting_ajax_list",
    ),
    path(
        "accounting/income/create/",
        accounting.AccountingIncomeCreateView.as_view(),
        name="accounting_income",
    ),
    path(
        "accounting/income/create/<int:bank_book_pk>/",
        accounting.AccountingIncomeCreateView.as_view(),
        name="accounting_income_for_book",
    ),
    path(
        "accounting/expense/create/",
        accounting.AccountingExpenseCreateView.as_view(),
        name="accounting_expense",
    ),
    path(
        "accounting/<int:pk>/detail/",
        accounting.AccountingDetailView.as_view(),
        name="accounting_detail",
    ),
    path(
        "accounting/<int:pk>/update/",
        accounting.AccountingUpdateView.as_view(),
        name="accounting_update",
    ),
    path(
        "accounting/<int:pk>/delete/",
        accounting.AccountingDeleteView.as_view(),
        name="accounting_delete",
    ),
    path(
        "ajax/payment_items/select2/",
        accounting.PaymentItemSelect2View.as_view(),
        name="payment_item_select2",
    ),
    path(
        "ajax/managers/select2/",
        accounting.ManagerSelect2View.as_view(),
        name="manager_select2",
    ),
    # Payment receipts
    path(
        "payment_receipts/",
        payment_receipts.PaymentReceiptsListView.as_view(),
        name="payment_receipts_list",
    ),
    path(
        "payment_receipts/ajax",
        payment_receipts.PaymentReceiptsAjaxDatatableView.as_view(),
        name="payment_receipts_ajax_list",
    ),
    path(
        "payment_receipts/create/",
        payment_receipts.PaymentReceiptsCreateView.as_view(),
        name="payment_receipts_create",
    ),
    path(
        "payment_receipts/create/<int:bank_book_id>/",
        payment_receipts.PaymentReceiptsCreateView.as_view(),
        name="payment_receipts_create",
    ),
    path(
        "payment_receipts/<int:pk>/detail/",
        payment_receipts.PaymentReceiptsDetailView.as_view(),
        name="payment_receipts_detail",
    ),
    path(
        "payment_receipts/<int:pk>/update/",
        payment_receipts.PaymentReceiptsUpdateView.as_view(),
        name="payment_receipts_update",
    ),
    path(
        "payment_receipts/<int:pk>/delete/",
        payment_receipts.PaymentReceiptsDeleteView.as_view(),
        name="payment_receipts_delete",
    ),
    path(
        "ajax/bank_book_owner/<int:pk>/",
        payment_receipts.BankBookOwnerInfoView.as_view(),
        name="bank_book_owner_info",
    ),
    path(
        "ajax/tariff_services/",
        payment_receipts.TariffServicesView.as_view(),
        name="tariff_services",
    ),
    path(
        "ajax/flat_meter_readings/",
        payment_receipts.FlatMeterReadingsView.as_view(),
        name="flat_meter_readings",
    ),
    path(
        "ajax/service_unit/",
        payment_receipts.ServiceUnitView.as_view(),
        name="service_unit",
    ),
    path(
        "payment_receipts/<int:pk>/print/",
        payment_receipts.PaymentReceiptPrintView.as_view(),
        name="payment_receipts_print",
    ),
    path(
        "payment_receipts/<int:pk>/download/",
        payment_receipts.PaymentReceiptDownloadView.as_view(),
        name="payment_receipts_download",
    ),
    path(
        "payment_receipts/<int:pk>/email/",
        payment_receipts.PaymentReceiptEmailView.as_view(),
        name="payment_receipts_email",
    ),
    path(
        "ajax/get-sections/", meter_readings.get_sections, name="get_sections"
    ),
    path("ajax/get-floors/", meter_readings.get_floors, name="get_floors"),
    path("ajax/get-flats/", meter_readings.get_flats, name="get_flats"),
]
