# Generated by Django 5.2.11 on 2026-02-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="roles",
            name="has_meter_readings",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="roles",
            name="has_payment_details",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="roles",
            name="has_requests",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="roles",
            name="has_roles",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="roles",
            name="has_services",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="roles",
            name="has_site_management",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="roles",
            name="has_tariffs",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="roles",
            name="has_users",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="users",
            name="external_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
