# Generated by Django 5.2.11 on 2026-02-11 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0002_initial'),
        ('finances', '0001_initial'),
        ('settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accounting',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounting_manager_rows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accounting',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounting_owner_rows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accounting',
            name='payment_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounting_rows', to='settings.paymentitems'),
        ),
        migrations.AddField(
            model_name='bankbook',
            name='flat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_book', to='buildings.flats'),
        ),
        migrations.AddField(
            model_name='accounting',
            name='bank_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounting_rows', to='finances.bankbook'),
        ),
        migrations.AddField(
            model_name='message',
            name='flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='buildings.flats'),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_readings', to='buildings.flats'),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='meter_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meter_readings', to='settings.services'),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='bank_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_receipts', to='finances.bankbook'),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_receipts', to='buildings.flats'),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_receipts', to='settings.tariffs'),
        ),
        migrations.AddField(
            model_name='paymentreceiptservice',
            name='payment_receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finances.paymentreceipt'),
        ),
        migrations.AddField(
            model_name='paymentreceiptservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_lines', to='settings.services'),
        ),
        migrations.AddField(
            model_name='request',
            name='flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='buildings.flats'),
        ),
    ]
